### ISSUE TITLE
Convert Vitepress scripts to ESM before CJS support is dropped

### ISSUE THREAD

**Issue by benmccann** [andatoshiki/toshiki-notebook#78]
This line will soon break:

https://github.com/andatoshiki/toshiki-notebook/blob/2a2cab88614cc8830fd0dc89be64bee748b7d70b/docs/.vitepress/utils/posts.data.js#L4

**Comment by andatoshiki** [comment]
Hi, the documentation post sitemap data generation feature is currently in experimental stage which indicating I shameful ripped the piece of code from other's project with the similar approach and plainly plugged the code into my own project, I have't turn such feature on because I personally tested such additional CJS scripts for achieving non-native feature for vitepress and it build end consistently fails on the current version upon the dependencies of the project, I ended up abstaining but still leaving as a legacy copy for references if I do want to implement it again in future. If you are looking for similar sitemap generation or data processing feature below is a list of recommended project with customized theme configs which are good starter point for you to dive into if you no clues nor directions on achieving the goals, but thanks for reminder anyways `:)`.
- https://github.com/Charles7c/charles7c.github.io
  I was completely naive to VitePress without a single sense of knowledge on TypeScript and here's the project where I started decomposing theme customizations done by the developers, some of my Vue template is a direct copy-paste from the repo with minor deletions.
- https://github.com/vuejs/vitepress/issues/520
  Here's the GitHub issue regarding sitemap generation feature integration mainly on modifying `buildend` property for avoiding ruthless unexpected errors while injecting non-compatible scripts similar to my approach.
- https://github.com/chodocs/chodocs
  Yet another elegant customized documentation site with adjusted customizations towards own need for showcasing personal knowledge bases, I haven't went deep into the project, but I'm pretty sure it's a good starting point for your reference. The developers successfully achieved both documentation archive metadata generation and sitemap building feature if I'm not remembering anything wrong.
  
I'm closing this issue because I don't have much intention or future plans to reuse the feature but as redundant references from elder version.
